main: fun.fifu.fifusky.FiFuSky
name: FiFuSky
version: ${version}
api-version: ${api_version}
author: NekokeCore
commands:
  s:
    description: "主命令"
    usage: 命令输入有误！ /s help [命令] 查看帮助
  fs-admin:
    description: "管理员命令"
    usage: 命令输入有误！ /fs-admin help [命令] 查看帮助
